theme: jekyll-theme-slate
title: Marcus L. Hynfield
description: 513.857.8707<br><a href="mailto:marcus@hynfield.org">marcus@hynfield.org</a><br><a href="https://www.linkedin.com/in/marcushynfield">LinkedIn</a>