theme: jekyll-theme-slate
title: Marcus L. Hynfield
description: 513.857.8707 | <a href="mailto:marcus@hynfield.org">marcus@hynfield.org</a> | <a href="https://www.linkedin.com/in/marcushynfield">LinkedIn</a>