name: Markdown Lint
on:
  push:
    branches: 
      - develop
    paths:
      - '**.md'
  pull_request:
    branches:
      - develop
      - master
    paths:
      - '**.md'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Lint index.md
      uses: avto-dev/markdown-lint@v1.5.0
      with:
        args: './'
